SimplyAdmire:
  CR:
    commandHandlers:
      'CommandFQDN0': 'Callable'
      'CommandFQDN1':
        - 'CallableClassName'
        - 'CallableMethodName'
      'CommandFQDN2': 'CallableClassName::CallableMethodName'
